// ============================================================
//  LV Books — Dados do app
//  Edite aqui para adicionar/remover audiobooks, eBooks e bônus
// ============================================================

// Para links do Google Drive use o formato:
//   https://drive.google.com/uc?export=download&id=SEU_FILE_ID
// O FILE_ID está na URL de compartilhamento:
//   drive.google.com/file/d/  >FILE_ID<  /view

var LVData = {

  // ── AUDIOBOOKS ────────────────────────────────────────────
  audiobooks: [
    {
  id: 1,
  title: '1 Ano em 12 Semanas - Brian P. Moran e Michael Lennington',
  author: '',
  cover: 'https://m.media-amazon.com/images/I/716Xx+6GJiS.jpg',
  audio: 'https://drive.google.com/file/d/1Kz-vm_bTi7mt6o0oLLqZ74Iwx3QErz3M/view?usp=drive_link'
},
    { id: 2, title: '100 Homens que a História do Mundo - Bill Yenne', author: '', cover: 'https://m.media-amazon.com/images/I/511fsUG82UL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1atURJtgR-AOVtkgZ_1CbPJjHHoIEpL1X/view' },
    { id: 3, title: '12 Regras para a Vida - Jordan B. Peterson - Parte 1 de 2', author: '', cover: 'https://m.media-amazon.com/images/I/71geoUmEoQL.jpg', audio: 'https://drive.google.com/file/d/10yU_goy4KK-2e-FvVydMhyi8FJN0kVxg/view?usp=drive_link' },
    { id: 4, title: '12 Regras para a Vida - Jordan B. Peterson - Parte 2 de 2', author: '', cover: 'https://m.media-amazon.com/images/I/71geoUmEoQL.jpg', audio: 'https://drive.google.com/file/d/1XE1yWUCcc8NAF8FVVC0au4YcyijBgCGK/view?usp=drive_link' },
    { id: 6, title: '12 Semanas Para Mudar Uma Vida - Augusto Cury', author: '', cover: 'https://m.media-amazon.com/images/I/61x7NtR5IoL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1sXYJZpI6aNsy4T_e8JNpX0Dz2p8iMuoX/view?usp=drive_link' },
    { id: 7, title: '1984 - George Orwell', author: '', cover: 'https://m.media-amazon.com/images/I/61t0bwt1s3L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1LyzP-97-65kJGk9-9AdN1745NzLsIpbn/view?usp=drive_link' },
    { id: 8, title: '23 Hábitos Anti-Procrastinação - S.J. Scott', author: '', cover: 'https://m.media-amazon.com/images/I/81lwpqg9QjL._UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1Xh1OlEAaA_TfarpPvNDMP1pzqdhEwhDa/view?usp=drive_link' },
    { id: 9, title: '27 Poderes de Persuasão - Chris St. Hilaire e Lynette Padwa', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2bL_-OhoNbCSf96P3ygEtpjyUzkNn_mPCMA&s', audio: '' },
    { id: 10, title: '29 Minutos para Falar Bem em Público - Reinaldo Piloto e Rachel Polito', author: '', cover: 'https://m.media-amazon.com/images/I/51s91VGATPL.jpg', audio: 'https://drive.google.com/file/d/1K9wJzz0XlpY3Yf10pEvGS7h6JOuoLbGi/view?usp=drive_link' },
    { id: 11, title: '38 Estratégias para Vencer Qualquer Debate - Arthur Schopenhauer', author: '', cover: 'https://m.media-amazon.com/images/I/A1yeZ0JiKzL._UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/14_iI0jG0zHy5ikRK3PCVwJZ_wWaNzykw/view?usp=drive_link' },
    { id: 12, title: '52 Maneiras de Ganhar Mais Dinheiro - Clene Salles', author: '', cover: 'https://m.media-amazon.com/images/I/81k7SgjSQfL._UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1jZG_LYvFxdejZjT6bQRXeHfGZ6CmeFfY/view?usp=drive_link' },
    { id: 13, title: '60 Estratégias Práticas para Ganhar mais Tempo - Christian Barbosa', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTI516sXanP3GQftQFvg-EhhbKfhVsrBwd6mQ&s', audio: 'https://drive.google.com/file/d/1Njn65RTsBWXtmvkE_M5M9aHaOpSCkkC_/view?usp=drive_link' },
    { id: 14, title: '7 Lições De Negócios De La Casa De Papel - Fabio Bandeira de Melo', author: '', cover: 'https://m.media-amazon.com/images/I/61Pj39C0npL.jpg', audio: 'https://drive.google.com/file/d/1sUXeOitWJWeNdrmcACUdWF3Ayb00Ce_8/view?usp=drive_link' },
    { id: 15, title: 'A Arquitetura do Eu - Leonardo Mascaro', author: '', cover: 'https://m.media-amazon.com/images/I/81ckGa4rTGL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1e-ddtMuWGAddAqU25JOp_49Q4_20u31H/view?usp=drive_link' },
    { id: 16, title: 'A Arte da Guerra - Sun Tzu', author: '', cover: 'https://m.media-amazon.com/images/I/51Fe45NGwkL.jpg', audio: 'https://drive.google.com/file/d/1XlHo8yoEyc8VW4W8UuB27GKGKFdcdUV2/view?usp=drive_link' },
    { id: 17, title: 'A Arte da Negociação - Donald Trump', author: '', cover: 'https://m.media-amazon.com/images/I/71rFjbVqioL.jpg', audio: 'https://drive.google.com/file/d/1NYP84rtPqJjiwxgPMn8WYiIM0vXGO8ZS/view?usp=drive_link' },
    { id: 18, title: 'A Arte da Sedução - Robert Greene', author: '', cover: 'https://m.media-amazon.com/images/I/61rQikkGR9L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/19kh4k3aip4WDgYqKQh5TWZEPIdVGR4qE/view?usp=drive_link' },
    { id: 19, title: 'A Arte de Escrever para Web - Paulo Macedo', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxreQW3zOmr5EAdEqRvCz_SdzwVYOTJnwEvA&s', audio: 'https://drive.google.com/file/d/1WVdmLaONNTOXS-MF16__s6_6reNjInS9/view?usp=drive_link' },
    { id: 20, title: 'A Arte de Viver - Epicteto - Audiobook Completo', author: '', cover: 'https://m.media-amazon.com/images/I/81G1s-jiYKL._UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1H-_ImhJbAI1esuA5i2_I3y8KLNsO28Qu/view?usp=drive_link' },
    { id: 22, title: 'A Árvore do Dinheiro - Jurandir Sell Macedo Jr', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwJnz2PkM7JKj03RyhLRhJU-Vr6bF4jwbeUw&s', audio: 'https://drive.google.com/file/d/132t1n18cl6S1R9EvYhE_a8V54ohMGGjh/view?usp=drive_link' },
    { id: 23, title: 'A Ascensão do Dinheiro - Niall Ferguson', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-VgKj3LvySGq314tQBCgeVtgig0Qvjc5h_Q&s', audio: 'https://drive.google.com/file/d/1pYASnoViHB8R6t15vnR7pTUd6ScfVaZI/view?usp=drive_link' },
    { id: 24, title: 'A Cabala do Dinheiro - Nilton Bonder', author: '', cover: 'https://m.media-amazon.com/images/I/51JdilXoweL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/11ObupMlnX0zvI7R3jVjQzb1vnwF0Hx0n/view?usp=drive_link' },
    { id: 25, title: 'A Cabana - William P. Young', author: '', cover: 'https://m.media-amazon.com/images/I/91fLBlcmpXL.jpg', audio: 'https://drive.google.com/file/d/1bRUiRNuaruSL000csSfhGK3fLDSQtqI9/view?usp=drive_link' },
    { id: 26, title: 'A Cabeça de Steve Jobs - Liderança', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZ1gI-2-SwlsnN2iM8B1FIxRF7GQKTmYAiRw&s', audio: 'https://drive.google.com/file/d/1h7J5z0ZmLm7IH_ex3bTuONOjy5VFdb2x/view?usp=drive_link' },
    { id: 27, title: 'A Cabeça Do Investidor - Vera Rita de Mello Ferreira', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6JR45MwAkr6Bq2Ymok5k_3L_LJ0yw6uO-Ew&s', audio: 'https://drive.google.com/file/d/1_J85qd3xQGb-8ke6Xf-SQPXylwHb-Izk/view?usp=drive_link' },
    { id: 28, title: 'A Chave Mestra das Riquezas - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/61HWnfnDrWS._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1sSz4vMkrIMcfL2eX7HWxoltyoOev_rku/view?usp=drive_link' },
    { id: 29, title: 'A Chave Mestra do Universo - Pablo Marçal', author: '', cover: 'https://m.media-amazon.com/images/I/712qlBX9PzL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1jTNa0_oWePT8NAcoZla1X2Iu2wGQfmH8/view?usp=drive_link' },
    { id: 31, title: 'A Chave para a Prosperidade - Napoleon Hill', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS94P7WdlRzw3Rc68IV9u8lH93BlWKIBPpnBQ&s', audio: 'https://drive.google.com/file/d/1sSz4vMkrIMcfL2eX7HWxoltyoOev_rku/view?usp=drive_link' },
    { id: 32, title: 'A Ciência de Ficar Rico - Wallace D. Wattles', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAFKISyDhkg_6FLpK3ETRp0k2P4eFXXqF-1g&s', audio: 'https://drive.google.com/file/d/1wO7Me85WzRo2cDDd5idfjBGm6ZXoyzjK/view?usp=drive_link' },
    { id: 34, title: 'A Ciência do Sucesso - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/91FQBKRKkKL.jpg', audio: 'https://drive.google.com/file/d/1wO7Me85WzRo2cDDd5idfjBGm6ZXoyzjK/view?usp=drive_link' },
    { id: 35, title: 'A Coragem de Ser Imperfeito - Brené Brown', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfSCSaBXxJc22xpiMR9XMq5h7QbBvLReipBA&s', audio: 'https://drive.google.com/file/d/1UmEh6mcFrcv4ahCaOBipDgkJk1J3I07D/view?usp=drive_link' },
    { id: 36, title: 'A Escada para o Triunfo - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/61OeOmvi1ZL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1_fBfqry_jSDthq9Jr6f5dB_uZ1EMsF6S/view?usp=drive_link' },
    { id: 38, title: 'A Estratégia do Oceano Azul - Renée Mauborgne, W. Chan Kim', author: '', cover: 'https://m.media-amazon.com/images/I/71zvq8BIkmL._AC_UF1000,1000_QL80_.jpg', audio: 'https://m.media-amazon.com/images/I/71zvq8BIkmL._AC_UF1000,1000_QL80_.jpg' },
    { id: 39, title: 'A Fascinante Construção Do Eu - Augusto Cury', author: '', cover: 'https://m.media-amazon.com/images/I/61HFLB5b5aL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1yELAVkGz6HVRJ2o_KEPLFVvJ-0HziK5j/view?usp=drive_link' },
    { id: 40, title: 'A Filosofia Do Sucesso - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/51heT5W9YUL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1-UkSv3bBWZznRrfqaEnpuKcM76AyrvLH/view?usp=drive_link  ' },
    { id: 41, title: 'A Introdução Definitiva a PNL - Richard Bandler', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2pL_8SxSvgu_o-W-8dDk29ej6afLUA8A57g&s', audio: 'https://drive.google.com/file/d/1k2rf-vxKiu7ZZVaks4guz1cyA-oHl8BQ/view?usp=drive_link' },
    { id: 43, title: 'A Lei da Atração - O Segredo Colocado em Prática - Michael J. Losier', author: '', cover: 'https://m.media-amazon.com/images/I/71aphXwg+bL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1WZO-iOY9Of6uk9bvpEOyvcYRiOwKkzCm/view?usp=drive_link' },
    { id: 44, title: 'A Marca da Vitória - A História da NIKE - Philip H. Knight', author: '', cover: 'https://http2.mlstatic.com/D_NQ_NP_821751-MLA79585916267_092024-O.webp', audio: 'https://drive.google.com/file/d/17GGrjhKFJqXgVZ40YoTHuCpeXRYQBWI-/view?usp=drive_link' },
    { id: 45, title: 'A Mente Acima do Dinheiro - Faça as Pazes com seu Dinheiro - Ted Klontz, Brad Klontz', author: '', cover: 'https://m.media-amazon.com/images/I/61T1NwrRmAL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/10No1p0ZgEMV2OVKi2LXV6OI4PIntmSMI/view?usp=drive_link' },
    { id: 47, title: 'A Morte é um Dia que Vale a Pena Viver - Ana Cláudia Quintana Arantes', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRt7WmzUW3GS8qIH-QgKcMT2Lg5eqtp_ZFrzQ&s', audio: 'https://drive.google.com/file/d/1cgyEJszzhm5fNSJkppHXbtRBQjE32Sic/view?usp=drive_link' },
    { id: 48, title: 'A Mágica da Arrumação - Marie Kondo', author: '', cover: 'https://m.media-amazon.com/images/I/81HKBLcErZL.jpg', audio: 'https://drive.google.com/file/d/1ct91EMp6bwjhUQM7ztCJJNfxSdOWyfkV/view?usp=drive_link' },
    { id: 49, title: 'A Paixão Segundo G.H. - Clarice Lispector', author: '', cover: 'https://m.media-amazon.com/images/I/71MOAylrC+L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/17zuGd3vmqKnbJZ93FRtfa6Knw1BOhqYD/view?usp=drive_link' },
    { id: 50, title: 'A Psicologia Financeira - Morgan Housel', author: '', cover: 'https://m.media-amazon.com/images/I/71vZp6yONLL.jpg', audio: 'https://drive.google.com/file/d/1r0f3sf8MrqJ1KecABrRVdtpxDzexttcZ/view?usp=drive_link' },
    { id: 51, title: 'A Realização Espontânea do Desejo - Deepak Chopra', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJV37zn_rzXYW4VBROW2yvC-K4iH-St9qhYw&s', audio: 'https://drive.google.com/file/d/1EyqR_YzideDCbj_uCi1lJWIhHakNh7l0/view?usp=drive_link' },
    { id: 52, title: 'A Revolução 8020, O Poder da Escolha - Richard Koch', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFHCaH9cYuC93n80CaK2Q0EI3MkjBPGxmTZw&s', audio: 'https://drive.google.com/file/d/1kFvrdUkQRF6Cn9ECATjBmjo5D5s0oT6F/view?usp=drive_link' },
    { id: 53, title: 'A Revolução dos Bichos - George Orwell', author: '', cover: 'https://m.media-amazon.com/images/I/91BsZhxCRjL.jpg', audio: 'https://drive.google.com/file/d/1ZdqF6EaLAlk5ft67puGfB7L_NgIvq6gu/view?usp=drive_link' },
    { id: 54, title: 'A Sorte Segue a Coragem - Mario Sergio Cortella', author: '', cover: 'https://m.media-amazon.com/images/I/81LVMS26UtL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1evaz-F2HPrMmwtgtuG6iai82L-cs8nMh/view?usp=drive_link' },
    { id: 56, title: 'A Sutil Arte de Ligar o Foda-se - Mark Manson', author: '', cover: 'https://m.media-amazon.com/images/I/6175IU0qFgL.jpg', audio: 'https://drive.google.com/file/d/1y0WXuBt7et2j64Q6ATK68Z0DVUui2eAj/view?usp=drive_link ' },
    { id: 57, title: 'A Tríade do Tempo - Christian Barbosa', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsjB0-9dbeK3Ni5qLiQVmFcZdC8OlxnaVBmA&s', audio: 'https://drive.google.com/file/d/1T-T-atbkCw_13vUdi_wX2f6Xuce4GVOV/view?usp=drive_link' },
    { id: 58, title: 'Admirável Mundo Novo - Aldous Huxley', author: '', cover: 'https://m.media-amazon.com/images/I/61hOp6UFvCL._AC_UF1000,1000_QL80_DpWeblab_.jpg', audio: 'https://drive.google.com/file/d/13yXJUO8GaG9KDhFc3whdfdBiBWCc2JFw/view?usp=drive_link' },
    { id: 59, title: 'Antimedo - Pablo Marçal', author: '', cover: 'https://m.media-amazon.com/images/I/61BsXDaRO8L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1cvOjlQRMa58ZRTSdo7Wbr2pXZ3VVFIkk/view?usp=drive_link' },
    { id: 60, title: 'Arriscando a Própria Pele - Nassim Nicholas Taleb', author: '', cover: 'https://m.media-amazon.com/images/I/61sb8kdjBqL.jpg', audio: 'https://drive.google.com/file/d/1YIfYsgfztoEEZpXMYaBv4ykB7akwZ8T9/view?usp=drive_link' },
    { id: 61, title: 'Arrume a Sua Cama - William H. McRaven', author: '', cover: 'https://m.media-amazon.com/images/I/81C7jAnjS3L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/112iwSVHfc6uu05N3Gqo3BLNi7_fWNioG/view?usp=drive_link' },
    { id: 62, title: 'As 21 Indispensáveis Qualidades de um Líder - John C. Maxwell', author: '', cover: 'https://m.media-amazon.com/images/I/81QzYgUjxRL.jpg', audio: 'https://drive.google.com/file/d/1cOKceECN_98Zub7A22d00fZUGFOL-2I7/view?usp=drive_link' },
    { id: 63, title: 'As 25 Leis Bíblicas do Sucesso', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMjIL1HicwlbpxhEgG13DKryAQMM210L9DQw&s', audio: 'https://drive.google.com/file/d/1rV1etFcjbO1uIjI4ebHWaI1hqwK-uUOk/view?usp=drive_link' },
    { id: 64, title: 'As 48 Leis do Poder - Robert Greene', author: '', cover: 'https://m.media-amazon.com/images/I/617iS--XOQL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1pvqhnZz4DkDxOhUjb0hgUdlPd-Z6wQTM/view?usp=drive_link' },
    { id: 65, title: 'As 5 Linguagens do Amor - Gary Chapman', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQloiykwmpNvCDRHqhKQqboT5crjBTirJfbHg&s', audio: 'https://drive.google.com/file/d/1Ph0uDhBIAqw4aDbXvnC_dQbzAd1vZs9K/view?usp=drive_link' },
    { id: 66, title: 'As Armas da Persuasão - Robert B. Cialdini', author: '', cover: 'https://m.media-amazon.com/images/I/71mWm5Oq7cL.jpg', audio: 'https://drive.google.com/file/d/1S6vtKdGEoz4l_c30jgKfaF11nRFglGOf/view?usp=drive_link' },
    { id: 67, title: 'As Cinco Habilidades Essenciais do Relacionamento - Dale Carnegie', author: '', cover: 'https://m.media-amazon.com/images/I/811M8IvYu0L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/140uee_EP2wl9Yv3mIHZhWUPakFjTAUpV/view?usp=drive_link' },
    { id: 68, title: 'As Coisas Que Você Só Vê Quando Desacelera - Haemin Sunim', author: '', cover: 'https://m.media-amazon.com/images/I/61F6T1at-nL.jpg', audio: 'https://drive.google.com/file/d/1jKd5AJR7dMtJa33kelYoGk5_se5dMkIT/view?usp=drive_link' },
    { id: 69, title: 'As Memórias de Sherlock Holmes - Arthur Conan Doyle', author: '', cover: 'https://m.media-amazon.com/images/I/81dM8mIahbL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1D2uLRd1y8CvwITg3Y417jOBpHiKUUDyZ/view?usp=drive_link' },
    { id: 70, title: 'As Regras Básicas de Warren Buffett - Jeremy C. Miller', author: '', cover: 'https://www.record.com.br/products/as-regras-basicas-de-warren-buffett', audio: 'https://drive.google.com/file/d/17iqAmZY5r_lFvENAo1xGfe8zIJZOYk3n/view?usp=drive_link  ' },
    { id: 71, title: 'As Regras de Ouro dos Casais Saudáveis - Augusto Cury', author: '', cover: 'https://m.media-amazon.com/images/I/61J2127-lyL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1wIRUpJ9Nen3GheP93L8eUw3neXOAFLqx/view?usp=drive_link' },
    { id: 72, title: 'Assim Falou Zaratustra - Friedrich Nietzsche', author: '', cover: 'https://m.media-amazon.com/images/I/91t6qaIZFWL.jpg', audio: 'https://drive.google.com/file/d/1N9SWsBS9VEsd5uemoeyvbqUlCNJmdFUC/view?usp=drive_link' },
    { id: 73, title: 'Assuma o Controle Do Seu Tempo - Holly Reisem Hanna', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZ1rklOenPYmFEFifCjgIvhtfQEBTzCxWipQ&sg', audio: 'https://drive.google.com/file/d/1igF6oN4PHCkCqZT0ycIUhCNShdHVX2Y4/view?usp=drive_link' },
    { id: 74, title: 'Atitude Mental Positiva - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/61vQc-iTKNL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1SR1fqwFZGUtGF_0umWgy1jpHz3DTnI3-/view?usp=drive_link' },
    { id: 75, title: 'Sobre a Brevidade da Vida - Caminhos da Sabedoria em Áudio', author: '', cover: 'https://m.media-amazon.com/images/I/71p7I8m6i8L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1U4QJQtVyhSn7q5KtOtGs0sb_7kT9jfaP/view?usp=drive_link' },
    { id: 76, title: 'Bitcoin - A Moeda na Era Digital - Fernando Ulrich', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8FdwkDFcSOcLtfQSN-YKzBoGiOtDshQcBJg&s', audio: 'https://drive.google.com/file/d/1MwFYFzTbfWp1GbdbHhSnpZq4-rjv6rKD/view?usp=drive_link' },
    { id: 77, title: 'Capitão da Minha Alma - Seja Dono da Sua Própria Mente - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/91UKLTjWpYL.jpg', audio: 'https://drive.google.com/file/d/15xlV64iPz63f_wQt0gqk65xUDrS4cZLc/view?usp=drive_link' },
    { id: 78, title: 'Cartas A Um Jovem Investidor - Gustavo Cerbasi', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvZfjj3Ds3ZySjUvXFK61cdCwPGQe2CvHuhQ&s', audio: 'https://drive.google.com/file/d/1G7E-E7tLuRAC6qGFhjon20h013YQOctd/view?usp=drive_link' },
    { id: 79, title: 'Cartas de um Diabo a seu Aprendiz - C. S. Lewis', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsQIkuGkXrztKMUd94JIeazlblHB1yEHyiLA&s', audio: 'https://drive.google.com/file/d/1R37W-xdcYN4QA3ut_aDd1gLqVwpu6ax4/view?usp=drive_link' },
    { id: 80, title: 'Casais Inteligentes Enriquecem Juntos - Gustavo Cerbasi', author: '', cover: 'https://m.media-amazon.com/images/I/71w3iodHVML._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1Z077vdGOLluTPbdPIRb0CqaB1AuN6wo6/view?usp=drive_link' },
    { id: 81, title: 'Casamento Blindado - Renato e Cristiane Cardoso', author: '', cover: 'https://m.media-amazon.com/images/I/61XLNeez93L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1fOUZIrbxSzvdS7YXOj2pReJFDHEeOcnr/view?usp=drive_link' },
    { id: 82, title: 'Comece Pelo Mais Difícil - Brian Tracy', author: '', cover: 'https://m.media-amazon.com/images/I/61rvWTjvMeL.jpg', audio: 'https://drive.google.com/file/d/1A5-oakKDKExr2icVBErc6jDzbbqoT4xs/view?usp=drive_link' },
    { id: 83, title: 'Comece Pelo Porquê - Simon Sinek', author: '', cover: 'https://m.media-amazon.com/images/I/71M6czhxmTL.jpg', audio: 'https://drive.google.com/file/d/1kURn0MS9r1jHiKP7cgo3gucX1SijGj4z/view?usp=drive_link' },
    { id: 84, title: 'Como Aprendi a Pensar - Luiz Felipe Pondé', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoTSo2ZnKgE3u3oZgkoihLiJG2ltyevjZqVg&s', audio: 'https://drive.google.com/file/d/13BKTycIRvVtCnuBt5nSVLNYVP6K6sQf_/view?usp=drive_link' },
    { id: 85, title: 'Como Atrair Dinheiro - Joseph Murphy', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 86, title: 'Como Aumentar o Seu Próprio Salário - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/81jOMSfVdkL._UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1zfnZ8E0n646L13wgmpwNaq4sRiKhq0Ug/view?usp=drive_link' },
    { id: 87, title: 'Como Chegar ao Sim - William Ury, Roger Fisher', author: '', cover: 'https://m.media-amazon.com/images/I/81ydaXHpiBL.jpg', audio: 'https://drive.google.com/file/d/1-TTWUshXzPe76Ir5TzCcP3_TRvYsXGet/view?usp=drive_link' },
    { id: 88, title: 'Como Convencer Alguém em 90 Segundos - Nicholas Boothman', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSulPeRTepdH8E__JfhERdyoRqCFH1g5-mfjw&s', audio: 'https://drive.google.com/file/d/1zQ0qtErdVco-LzR6jjD7mjyGQQyj5i4s/view?usp=drive_link' },
    { id: 89, title: 'Como Evitar Preocupações e Começar a Viver - Dale Carnegie', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 90, title: 'Como Fazer Alguém Gostar de Você em 90 Segundos - Nicholas Boothman', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 91, title: 'Como Fazer Amigos e Influenciar Pessoas - Dale Carnegie', author: '', cover: 'https://m.media-amazon.com/images/I/71x-i7sKSvL.jpg', audio: 'https://drive.google.com/file/d/1rxtIfkOoGPEgXxyMPBMwKVSBXEMedSgA/view?usp=drive_link' },
    { id: 92, title: 'Como Ganhar Dinheiro na Internet - 45 Formas Comprovadas - Thiago Vertad', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTylImkQ9T08QF6Qgwnkxe3f-rhWugq2e1D2w&s', audio: 'https://drive.google.com/file/d/1ScTSaUW5OMF7pTNhJflX4ksmaxYrPPO3/view?usp=drive_link' },
    { id: 93, title: 'Como Lidar Com Pessoas Manipuladoras - George K. Simon', author: '', cover: 'https://m.media-amazon.com/images/I/714eNmAFaeL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/15rZPBYpQU_vFidNyt0t3F3rGhJkLQGDh/view?usp=drive_link' },
    { id: 94, title: 'Como Organizar Sua Vida Financeira - Gustavo Cerbasi', author: '', cover: 'https://m.media-amazon.com/images/I/71Mhl0pI8XL.jpg', audio: 'https://drive.google.com/file/d/1HJdvWQYzL7k9Qj4k_QAQ8-SlDjLb87vd/view?usp=drive_link' },
    { id: 95, title: 'Como Parar de Se Preocupar e Começar a Viver - Dale Carnegie', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 96, title: 'Como Se Tornar Inesquecível - Dale Carnegie', author: '', cover: 'https://m.media-amazon.com/images/I/71cU-NxxSUL.jpg', audio: 'https://drive.google.com/file/d/1YPwRY26akSWWo-3FCQtyJi9OwIyZETJ7/view?usp=drive_link' },
    { id: 97, title: 'Como Ser um Imã para o Dinheiro - Bruno Gimenes', author: '', cover: 'https://m.media-amazon.com/images/I/913NsIKL2lL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/10rvEysd6wkK_YlVkt7GIwylPxnG_P-YR/view?usp=drive_link' },
    { id: 98, title: 'Como Vender Na Crise e Aumentar Seus Lucros - Magno A. Sipaúba', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4LSOon2kKDuvxyMybSwvrzaLvNIW_XHooQQ&s', audio: 'https://drive.google.com/file/d/1O0PFVw4RyZax8z59Uq_fMbIekoka2PF6/view?usp=drive_link' },
    { id: 99, title: 'Copywriting - Volume 2 - A Habilidade de Ouro Usada por Milionários - Paulo Macedo', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaJOXPF0uSTtGUNo4DqKruAwFPU0Vb2Yy0Pg&s', audio: 'https://drive.google.com/file/d/1l-zwY8RfZn9J88iEtFr5-WvLmjhPK3ll/view?usp=drive_link' },
    { id: 100, title: 'Crer ou Não Crer - Padre Fábio de Mello e Leandro Karnal', author: '', cover: 'https://m.media-amazon.com/images/I/81jdb7LlFTL._UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1RqRo65jWDNwsxCE-lZCSjEbru5deZUvT/view?usp=drive_link' },
    { id: 101, title: 'Criação de Riqueza - Uma Metodologia Simples e Poderosa - Paulo Vieira', author: '', cover: 'https://m.media-amazon.com/images/I/71SFDJSl-9L.jpg', audio: 'https://drive.google.com/file/d/1AZmqTBsIPQ4VpTJU4a77VhlDhBU_8Np7/view?usp=drive_link' },
    { id: 102, title: 'Curso Sobre Domínio Em Liderança - Dale Carnegie', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjS4IwL4bCnkSBVwf25Lzym1P3sbIXB0T_Sw&s', audio: 'https://drive.google.com/file/d/1qJRq7tMkJGfEw5jjBJZddeCQqdFPdecZ/view?usp=drive_link' },
    { id: 103, title: 'De Zero a Um - Peter Thiel', author: '', cover: 'https://m.media-amazon.com/images/I/71nURqHifwL.jpg', audio: 'https://drive.google.com/file/d/11lUOXRONCa1uZOuD2ynVgd0oroc-BIMA/view?usp=drive_link' },
    { id: 104, title: 'Decifre e Influencie Pessoas - Paulo Vieira', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0WY-6bDK5iEuUYcz6lA96WaIxTAvJrAbLHA&s', audio: 'https://drive.google.com/file/d/1ijU1sb7y3G7HSH7AuBgit1qiL91SHSqB/view?usp=drive_link' },
    { id: 105, title: 'Desbloqueie o Poder da Sua Mente - Michael Arruda', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS76mxrnSm43ItGXSDJz-vW8ezYiU7PyOPQKQ&s', audio: 'https://drive.google.com/file/d/1hkkO0AVN6NNa01lTh9aUlfMCOJVJBsHS/view?usp=drive_link' },
    { id: 106, title: 'Desperte o Milionário que Há em Você - Nicholas Boothman', author: '', cover: 'https://m.media-amazon.com/images/I/81eKzk+tnAL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1AG1J9hmjlxy-wTLFgMPnJB49q4aeDLA6/view?usp=drive_link' },
    { id: 107, title: 'Do Mil Ao Milhão - Thiago Nigro', author: '', cover: 'https://m.media-amazon.com/images/I/81r5VTxaBiL.jpg', audio: 'https://drive.google.com/file/d/1L6GoxR3jKzoZcgc6cHZHMYQPJGINpzuO/view?usp=drive_link' },
    { id: 108, title: 'Do Zero ao Milhão - Carlos Wizard', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSruzu6QtwL76E_tHQiTzl1ax2ZrDEWAOyMxg&s', audio: 'https://drive.google.com/file/d/1saBg6fOksBPWz71zsxpUw3peGUSwSt1z/view?usp=drive_link' },
    { id: 109, title: 'Empresas Feitas Para Vencer - Jim Collins', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN2SlbAZe4x6uR4L1nbVC6Pd3D7BGf5YPvuQ&s', audio: 'https://drive.google.com/file/d/1jdd4siu1PzBFRo9UYjC2cjCzfSqBlhT9/view?usp=drive_link' },
    { id: 110, title: 'Enriquecer - Ambição de Muitos, Realização de Poucos - Lair Ribeiro', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpzTtmID4kWm_tFgRO15agwAAplu9d5xjxVg&s', audio: 'https://drive.google.com/file/d/1qc7PF2v4CSWdgBXKUOUKswE0d_cE-kUG/view?usp=drive_link' },
    { id: 111, title: 'Escola de Negócios - Robert T. Kiyosaki', author: '', cover: 'https://m.media-amazon.com/images/I/71jUUjucszL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1FpCdZZSPCLRE7ZVtwsjxR0H4dUHW4ey0/view?usp=drive_link  ' },
    { id: 112, title: 'Especialista em Pessoas - Tiago Brunet', author: '', cover: 'https://m.media-amazon.com/images/I/81A6qTcEONL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1pKhgkNhdwa2-9B7JGFZ3iu9cJfEco3Dh/view?usp=drive_link' },
    { id: 113, title: 'Essencialismo - Greg McKeown', author: '', cover: 'https://m.media-amazon.com/images/I/71HuZRl-XeL.jpg', audio: 'https://drive.google.com/file/d/1Qjt_AisWNslkKLF6SsIDy6CkMQ46YXva/view?usp=drive_link' },
    { id: 114, title: 'Eu Vou te Ensinar a Ser Rico - Ben Zruel', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRE-Diiv7E0s1FMDxU2EpCKf-AHNO47n-5g2Q&s', audio: 'https://drive.google.com/file/d/13tlbuTYUJoWeMHAjklnHIeF74NE2OLkj/view?usp=drive_link' },
    { id: 115, title: 'Fator de Enriquecimento - Paulo Vieira', author: '', cover: 'https://m.media-amazon.com/images/I/81m-aKfHLlL.jpg', audio: 'https://drive.google.com/file/d/1LveT0OOWpPTGhV9OWN3e7JxqY-x5wVNO/view?usp=drive_link' },
    { id: 116, title: 'Faça Fortuna com Ações - Décio Bazin', author: '', cover: 'https://m.media-amazon.com/images/I/71VC1WBFjwL._UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1ogOLZ4KYHA-bdfLxrF2SSHNy7ScLmRuF/view?usp=drive_link' },
    { id: 117, title: 'Filhos Inteligentes Enriquecem Sozinhos - Gustavo Cerbasi', author: '', cover: 'https://m.media-amazon.com/images/I/61YE9CFh+7L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/16-7cHBtv9hwlRTG9kEpjIXLZQnPl5vos/view?usp=drive_link' },
    { id: 118, title: 'Foco - O Poder da Única Coisa - Vinicius Almeida', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 119, title: 'Gatilhos Mentais - Gustavo Ferreira', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgLccYBcNzmq26FLsDRSSgX_qrv8tMlWdOiQ&s', audio: 'https://drive.google.com/file/d/1AH6piox48dxiAhdg3XBeKRozk8i4sDzN/view?usp=drive_link' },
    { id: 120, title: 'Gente Pobre - Fíodor Dostoiévski', author: '', cover: 'https://m.media-amazon.com/images/I/81xrQauj0bL.jpg', audio: 'https://drive.google.com/file/d/1IsG52PBjIr2lBlsQAn6Y4puTil7nNzUg/view?usp=drive_link' },
    { id: 121, title: 'Geração de Valor - Flávio Augusto da Silva', author: '', cover: 'https://m.media-amazon.com/images/I/51D2KF-05oL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1-OdSLZa8XGdTf0W5EqfdzW-etR4LMDP-/view?usp=drive_link' },
    { id: 122, title: 'Hackeando Tudo - Raiam Dos Santos', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 123, title: 'Harry Potter e a Pedra Filosofal - J. K. Rowling', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 124, title: 'HomoDeus - Yuval Noah Harari', author: '', cover: 'https://m.media-amazon.com/images/I/81ql3Ty2O2L.jpg', audio: 'https://drive.google.com/file/d/1uvnBj95RMsXWpEGCpPXKlpFKskm7uHd3/view?usp=drive_link' },
    { id: 125, title: 'Hábitos Atômicos - James Clear', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 127, title: 'Hábitos Milionários - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/51O6kna8l2L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/11L9Mp1C3XzGfzwY51Y7wtsduqy6cjmlr/view?usp=drive_link' },
    { id: 128, title: 'Ikigai - Os Segredos Dos Japoneses Para Uma Vida Longa e Feliz - Hector Garcia, Francesc Miralles', author: '', cover: 'https://m.media-amazon.com/images/I/717ksSGStoL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1JhZ8jtX1re_HDxdIMBlz7sd_c4COjX_g/view?usp=drive_link' },
    { id: 129, title: "Limite Zero (Ho'oponopono) - Joe Vitale", author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKZKw_PqoQQhD_yRWWn_K7Rpos0eDqoJeoLg&s', audio: 'https://drive.google.com/file/d/1HVx3_o49r38bAUFNfFZT_k9342fhajuV/view?usp=drive_link' },
    { id: 130, title: 'Linguagem e Persuasão - Adilson Citelli', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShdmANas93ZjrMMO6iOWz5OP8En0oxPLlN1A&s', audio: 'https://drive.google.com/file/d/14b-F5zfQImlqTt3sMEixOvjR7NMaJJu4/view?usp=drive_link' },
    { id: 132, title: 'Mais Esperto que o Diabo - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/819ERrDHRcL.jpg', audio: 'https://drive.google.com/file/d/1khujfGhg9fz72qzL_lDQj-xHU2vHQ-FM/view?usp=drive_link' },
    { id: 133, title: 'Manual de Persuasão do FBI - Jack Shafer e Marvin Karlins', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9JoiEWTj8P0hGJUM4e_aXcEMh3sY-h4MFBg&s', audio: 'https://drive.google.com/file/d/1K5hEAY7vX0WsSf1gXOn0X9hyvXbEZAO6/view?usp=drive_link' },
    { id: 134, title: "Manual de Programação Neurolinguística PNL - Joseph O'Connor", author: '', cover: 'https://m.media-amazon.com/images/I/91C-ARCeEEL.jpg', audio: 'https://drive.google.com/file/d/1HBsnv5STPI6MJ6h0Gby9H48uTAOyhpdl/view?usp=drive_link' },
    { id: 135, title: 'Marketing 5.0 - Philip Kotler', author: '', cover: 'https://m.media-amazon.com/images/I/81CeGewVziL.jpg', audio: 'https://drive.google.com/file/d/15SaQ35IcqpX7GShOogQaCWh0dz_QSeW-/view?usp=drive_link' },
    { id: 136, title: 'Me Poupe! - Nathalia Arcuri', author: '', cover: 'https://m.media-amazon.com/images/I/51xb+0mEJvL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1D4HwlgEe-61jzTC3Ejm1ByMIh4AZXTaf/view?usp=drive_link' },
    { id: 137, title: 'Menos é Mais - Francine Jay', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxRr_5WzRsss2bzj-hZWRRDRna9GuJdUX0Zw&s', audio: 'https://drive.google.com/file/d/1YP_wYA41t6iWLhN1G4XgQjwf9toPFIlm/view?usp=drive_link' },
    { id: 138, title: "Mentes Brilhantes - Alberto Dell'Isola", author: '', cover: 'https://m.media-amazon.com/images/I/81BsIfwdODL._UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1xX-jfiKrJ4h6gSz9NpTTXqLqk359WSxY/view?usp=drive_link' },
    { id: 139, title: 'Mindset - A Nova Psicologia do Sucesso - Carol Dweck', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbNFK1rm0IgtA-DHF5kTFUV8JGsNgdAJOcoA&s', audio: 'https://drive.google.com/file/d/1o5rjkC8RKw4Ek3LmtEyc6CuMUEyY_i-_/view?usp=drive_link' },
    { id: 140, title: 'Mini Hábitos - Stephen Guise', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGFZE-ymJTTqu2NqUOWkiXHOPEpepsfTeTGQ&s', audio: 'https://drive.google.com/file/d/1YQUrBVhh2I7oyI-O41TTNoQbV5_djBko/view?usp=drive_link' },
    { id: 141, title: 'Moby Dick - Herman Melville', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 142, title: 'Nascido Para o Sucesso - Colin Turner', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 143, title: 'Nação Dopamina - Anna Lembke', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 144, title: 'Negocie Como se Sua Vida Dependesse Disso - Christopher Voss, Tahl Raz', author: '', cover: 'https://m.media-amazon.com/images/I/713A9sSxvRL.jpg', audio: 'https://drive.google.com/file/d/1oQXiqArQqaIbJ7QzFqbWViZrjoLxRQFJ/view?usp=drive_link' },
    { id: 145, title: 'Negocie Qualquer Coisa com Qualquer Pessoa - Eduardo Ferraz', author: '', cover: 'https://m.media-amazon.com/images/I/71M8uuTqyHL.jpg', audio: 'https://drive.google.com/file/d/1VmPb5fPqt4ROSfeRt-9zms03XgBurKeM/view?usp=drive_link' },
    { id: 146, title: 'Nocaute - Gary Vaynerchuk', author: '', cover: 'https://m.media-amazon.com/images/I/81JoRQMsSFL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1oDhIMGhJvBdxHz_AbOgxB7haFXdSbJ0A/view?usp=drive_link' },
    { id: 147, title: 'Nunca Desista De Seus Sonhos - Augusto Cury', author: '', cover: 'https://m.media-amazon.com/images/I/81p8yfg2qyL.jpg', audio: 'https://drive.google.com/file/d/1Jvrj7-JFiUl9jpa5DqjgkDwaL_yuQjv9/view?usp=drive_link' },
    { id: 148, title: "Nunca Foi Sorte - Adrianna Sant'anna", author: '', cover: 'https://m.media-amazon.com/images/I/51-sTZMJ91L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1GMkfAecRzr8HNi1kz2plT5Qp6lpPviTF/view?usp=drive_link' },
    { id: 149, title: 'Nós Queremos que Você Fique Rico - Donald Trump, Robert Kiyosaki', author: '', cover: 'https://m.media-amazon.com/images/I/61SAwym1QSL.jpg', audio: 'https://drive.google.com/file/d/1S822wV9NtAh9Oo1SDdafmyBRlTfzx4LU/view?usp=drive_link' },
    { id: 150, title: 'O Alquimista - Audiobook Completo - Narração Profissional', author: '', cover: 'https://acdn-us.mitiendanube.com/stores/003/717/513/products/81ihktjc-6l-_sl1500_-c6f569b7e6249046ad17386960141040-480-0.webp', audio: 'https://drive.google.com/file/d/16_YbtRBgRu9o0ctl09BKkCsBLicOmaJC/view?usp=drive_link' },
    { id: 151, title: 'O Banquete - Platão - Audiobook Completo', author: '', cover: 'https://m.media-amazon.com/images/I/81HQpUxYZDL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1FSCFx0WyzduBRZss42-MWrKsagIU3Tb8/view?usp=drive_link' },
    { id: 152, title: 'O Cavaleiro dos Sete Reinos - George R.R. Martin', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 153, title: 'O Clube Das 5 Da Manhã - Robin Sharma', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8D74FBkluGJAVvNq2nl8A2JX_PxDVmAEfdg&s', audio: 'https://drive.google.com/file/d/1DTkPFEumsn44SCLwT8KmKnnGs_NXb8zG/view?usp=drive_link' },
    { id: 155, title: 'O Corpo Fala - Pierre Weil e Roland Tompakow', author: '', cover: 'https://m.media-amazon.com/images/I/81bs2U1-CrL.jpg', audio: 'https://drive.google.com/file/d/1x49uisg06Pt2iXuLlIERc1Ua2bc3G8f1/view?usp=drive_link' },
    { id: 156, title: 'O Código da Inteligência - Augusto Cury', author: '', cover: 'https://m.media-amazon.com/images/I/71sabxRPQyL.jpg', audio: 'https://drive.google.com/file/d/1mq3WWqKwxK6AYUWOOluvH35BhR4tC449/view?usp=drive_link' },
    { id: 157, title: 'O Ego é Seu Inimigo - Ryan Holiday', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxhlclnDKuLxjmpDecgjhjqzkx4WvGsdNdxA&s', audio: 'https://drive.google.com/file/d/1-_f6mI9z2mG7ZccnfHKegFvQFRLaUNA0/view?usp=drive_link' },
    { id: 158, title: 'O Hobbit - Audiobook Completo - Narração Profissional', author: '', cover: 'https://m.media-amazon.com/images/I/91M9xPIf10L.jpg', audio: 'https://drive.google.com/file/d/1-MvbxLsBcF3Cf8OsZMU8ZUXS9p0btRVm/view?usp=drive_link' },
    { id: 159, title: 'O Homem Mais Inteligente da História - Augusto Cury', author: '', cover: 'https://m.media-amazon.com/images/I/61o3PuCiBEL.jpg', audio: 'https://drive.google.com/file/d/12_A8VwZeg0RNh7Sl5WfHNcivZB7vh0ds/view?usp=drive_link' },
    { id: 160, title: 'O Homem Mais Rico da Babilônia - George Samuel Clason', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS24gOqFwVpUrMQ5QaKMvY46QF2vU8hsiIFeA&s', audio: 'https://drive.google.com/file/d/1MQ_rKKyLriAMgBugiT1tsclq0NuuP6Ll/view?usp=drive_link' },
    { id: 161, title: 'O Homem é Aquilo que ele Pensa - James Allen', author: '', cover: 'https://m.media-amazon.com/images/I/61LyKRYv5CL.jpg', audio: 'https://drive.google.com/file/d/107TVEhdXlzFNiVlgQfuSZ0Pjk9ajpbp5/view?usp=drive_link' },
    { id: 162, title: 'O Jeito Disney de Encantar os Clientes - Disney Institute', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSjGvnN9FK5NuGbt3V1qs3Fja5vC3W2yBbVA&s', audio: 'https://drive.google.com/file/d/1xgRzxPt8_euiErvN29GixZuKDCJiQsWA/view?usp=drive_link' },
    { id: 163, title: 'O Lobo de Wall Street - Jordan Belfort', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 164, title: 'O Maior Vendedor do Mundo - Og Mandino', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1xXixJUMR_R7voSFUv7G1lZKnWfQi_H8m3g&s', audio: 'https://drive.google.com/file/d/1ctmbDp0ByqFF00iyxxx02XuB6PJlxQnx/view?usp=drive_link' },
    { id: 165, title: 'O Manuscrito Original - Napoleon Hill', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_esUHvP1Ujl-uebvPZYV72VyiahBKKatBsw&s', audio: 'https://drive.google.com/file/d/1zDPJoUArtmMw2oyw4GB1TvWVQWfOpBl5/view?usp=drive_link' },
    { id: 166, title: 'O Mensageiro Milionário - Brendon Burchard', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 167, title: 'O Milagre da Manhã - Hal Elrod', author: '', cover: 'https://m.media-amazon.com/images/I/512zQ6qXkML._AC_UF1000,1000_QL80_DpWeblab_.jpg', audio: 'https://drive.google.com/file/d/1g8GCXJLSpsZwdQHFWahBLHOizAE-C5BW/view?usp=drive_link' },
    { id: 168, title: 'O Milagre da Manhã para Transformar seu Relacionamento - Hal Elrod', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnXBw0g5-DxKB5XUFebAJBL_IEwCBrErfHPw&s', audio: 'https://drive.google.com/file/d/1ukpQolge3lOpJh_Qrx-FBkkHqTtbsHtD/view?usp=drive_link' },
    { id: 169, title: 'O Milionário Instantâneo - Marc Fisher', author: '', cover: 'https://m.media-amazon.com/images/I/91IpAi1T7bL._UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1lBYjvpK9UKv3_QHzz2eCOs8V3S2DVk9Z/view?usp=drive_link' },
    { id: 170, title: 'O Monge e o Executivo - James C. Hunter', author: '', cover: 'https://m.media-amazon.com/images/I/81azm3rAm3L.jpg', audio: 'https://drive.google.com/file/d/1AfPvx1MEyw_-QVWK0ueC_FFznc2Eaaxu/view?usp=drive_link' },
    { id: 171, title: 'O Negócio do Século XXI - Robert Kiyosaki', author: '', cover: 'https://altabooks.com.br/wp-content/uploads/2021/07/3D_Negocio_Seculo_XXI.jpg', audio: 'https://drive.google.com/file/d/1VN8RTgs8BV6e30I4mFmz--_2KG6RdkQ6/view?usp=drive_link' },
    { id: 172, title: 'O Pequeno Príncipe - Antoine de Saint-Exupéry', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 173, title: 'O Poder da Ação - Paulo Vieira', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0ox3dL0W7yoyoOWJxtawzLa8VHsmWi79MGQ&s', audio: 'https://drive.google.com/file/d/1dhisLXuxAXndDL5OW4IVY8wMtO7tZKJl/view?usp=drive_link' },
    { id: 174, title: 'O Poder da Resiliência - Rick Hanson', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 175, title: 'O Poder do Agora - Eckhart Tolle', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 177, title: 'O Poder do Hábito - Charles Duhigg', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmx_YFT8XXbKzQ9p5L00dsXDSAWa3x3NjCwQ&s', audio: 'https://drive.google.com/file/d/1k4auz-xOQjrKWwpdRS7WGoODEokA9Wbx/view?usp=drive_link' },
    { id: 178, title: 'O Poder do Subconsciente - Joseph Murphy', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuV60ZO3pvaKxJZlztfqaFuCS1yv95AQMjag&s', audio: 'https://drive.google.com/file/d/1M5dL75CAZkTFwMYwuJe6Pkf3iS3IBOR7/view?usp=drive_link' },
    { id: 179, title: 'O Poder dos 5 Segundos - Mel Robbins', author: '', cover: 'https://http2.mlstatic.com/D_NQ_NP_838240-MLB79609386924_102024-O.webp', audio: 'https://drive.google.com/file/d/1aZEIqDzjsqG_QMaxJft7WWKb2FL2L02h/view?usp=drive_link' },
    { id: 180, title: 'O Príncipe - Nicolau Maquiavel', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3XOUSG9uzKhAthtuBWUjEe6rKXBptbPP7Sg&s', audio: 'https://drive.google.com/file/d/11ImlOwvYtDgC7E7ynNjLXqItp3n3xbrZ/view?usp=drive_link' },
    { id: 182, title: 'O que Steve Jobs Faria - Peter Sander', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjwd-62tSvtUnpIt9iIt0Iby8xlXP0k6d0_w&s', audio: 'https://drive.google.com/file/d/1UR69UgpKkoRe_EU_0bwRZC6CneYVii3i/view?usp=drive_link' },
    { id: 183, title: 'O Segredo (The Secret) - Rhonda Byrne', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 184, title: 'O Senhor dos Anéis - Livro 1 - A Sociedade do Anel - J. R. R. Tolkien', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 185, title: 'O Senhor dos Anéis - Livro 2 - A Sociedade do Anel - J. R. R. Tolkien', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 186, title: 'O Sentimento é o Segredo - Neville Goddard', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 187, title: 'O Sucesso Não Ocorre Por Acaso - Lair Ribeiro', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 188, title: 'O Universo Numa Casca De Noz - Stephen Hawking', author: '', cover: 'https://m.media-amazon.com/images/I/61LGgb24eYL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1QhpRzL0Ng8nY_SkcFGiuluf0ZTwq0et8/view?usp=drive_link' },
    { id: 189, title: 'O Vendedor de Sonhos - Augusto Cury', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhrqjGxI6ptaZw8jizOPQ0eaXaLxFNtoLkZg&s', audio: 'https://drive.google.com/file/d/1Im0OpFcQ__xRVQ7fZj-TdrHB0hHilxcC/view?usp=drive_link' },
    { id: 190, title: 'O Vinho Novo é Melhor - Robert Thom', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdHuCEN60LD7BMZoNlUiF5Vpwd1qTBqgbe_g&s', audio: 'https://drive.google.com/file/d/1rGcE1V007TSs5zpiT36dUcZTaT3O_zkZ/view?usp=drive_link' },
    { id: 191, title: 'Opúsculo Humanitário - Parte 1', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQco_pbZtRxe-vpOMzLTyTHlPyhJZdi_4PHNA&s', audio: 'https://drive.google.com/file/d/1SlZwmwVvxuKSu62hDc6a_6ohyQtry872/view?usp=drive_link' },
    { id: 192, title: 'Opúsculo Humanitário - Parte 2', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQco_pbZtRxe-vpOMzLTyTHlPyhJZdi_4PHNA&s', audio: 'https://drive.google.com/file/d/1P9MPuWrWi3LV12TWWfu49IInaTx-e9Fb/view?usp=drive_link' },
    { id: 193, title: 'Originais - Adam Grant', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEk8Vg0c4h4eiycgvhhcDY4Zv7i3VzSZs02w&s', audio: 'https://drive.google.com/file/d/1AqJuPI_A4Z-yKoEXVM3hbK8R_Jt5QHae/view?usp=drive_link' },
    { id: 194, title: 'Os 100 Segredos Das Pessoas Felizes - David Niven', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA0nIubtGLRZnbPzKR_Kwx6-GByEK5rF5iMQ&s', audio: 'https://drive.google.com/file/d/1rTPmRFqUHF-j_kswhPZWR7MFchM0L6sF/view?usp=drive_link' },
    { id: 195, title: 'Os Códigos do Milhão - Pablo Marçal', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi9EShdRza4Zo_wiN78Sx2pOPVvGEBf-sxPg&s', audio: 'https://drive.google.com/file/d/1j4gxVh-GJAoAinZeKHuauu2c0MFJMkS_/view?usp=drive_link' },
    { id: 197, title: 'Os Segredos Da Mente Milionária - T. Harv Eker', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-AsuoWvicfcwHD3isVj-eZ48i-0XsmFbwnw&s', audio: 'https://drive.google.com/file/d/1QiWw_qOU_0LX7Tt76JhpkppvccySjLeB/view?usp=drive_link' },
    { id: 199, title: 'Pai Rico Pai Pobre - Robert Kiyosaki', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkUOcuoI076q-BUIRd_SroQy-DpZ3tV9Z-cw&s', audio: 'https://drive.google.com/file/d/1dlxhckgU_ZOg-CT76DVh6UdUiSC0wlQD/view?usp=drive_link' },
    { id: 201, title: 'Penso e Acontece - Bob Proctor', author: '', cover: 'https://m.media-amazon.com/images/I/51sgyZE4m7L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1e3h5PsCJl0z_e8JekWpBs9w5rP4xiYg-/view?usp=drive_link' },
    { id: 202, title: 'Poder e Manipulação - Jacob Petry', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXtJwPT9hBMAnYIcxJgoD76JiXyasN0f8S0g&s', audio: 'https://drive.google.com/file/d/1AAeV8XJr2nPcad3iM8vE9cSEr-tdhoJp/view?usp=drive_link' },
    { id: 203, title: 'Ponto de Inflexão - Flávio Augusto da Silva', author: '', cover: 'https://m.media-amazon.com/images/I/51EnbHAl1QL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1aC1g6ohkvXJZ0qOpgjJoArS7UkgKu6K4/view?usp=drive_link' },
    { id: 204, title: 'Por Que Fazemos O Que Fazemos - Mario Sergio Cortella', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQx0YPnxkbeUKpRs3sWPvDhzrhmFWXN4ypa4A&s', audio: 'https://drive.google.com/file/d/1pxORT8iOHITR7xz9lybGAbPLm8F706hA/view?usp=drive_link' },
    { id: 205, title: 'Prosperidade - 12 Passos para Alcançar o Sucesso - Charles Fillmore', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-9-ySW6BA9I-bzR983pOqMW5ViYzFq3zPKA&s', audio: 'https://drive.google.com/file/d/12MzXQGpSTYZHwpyq8B4g0PwOLH03gCgD/view?usp=drive_link' },
    { id: 206, title: 'Qual é a Tua Obra - Mário Sérgio Cortella', author: '', cover: 'https://m.media-amazon.com/images/I/81f5yhwfQmL.jpg', audio: 'https://drive.google.com/file/d/148zph7cslZ__YiE6eZPuemH9OIyvNgEU/view?usp=drive_link' },
    { id: 207, title: 'Quebrando o Hábito de Ser Você Mesmo - Joe Dispenza', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2BFjStBbp3p3oN_v4bGAQkDqFwdz_7Eti8A&s', audio: 'https://drive.google.com/file/d/12WM4nAe-3nkJgKCIlrEXmtk1Nj8H6tqm/view?usp=drive_link' },
    { id: 208, title: 'Quem Assiste Enriquece - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/61YvlLtD+oL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1hKFk_D4SgzYguYRenImKVbA56Xpnxpc4/view?usp=drive_link' },
    { id: 210, title: 'Quem Pensa, Enriquece - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/71ivq+NMtZL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1lt7pd5QKLk7h0bmR170yUoRfO-B-XETD/view?usp=drive_link' },
    { id: 211, title: 'Salomão, O Homem Mais Rico que Já Existiu - Steven K. Scott', author: '', cover: 'https://m.media-amazon.com/images/I/71TWVC8ehAL.jpg', audio: 'https://drive.google.com/file/d/1ESXzJaRL5ESZZocq_90545AXVy6U_tjJ/view?usp=drive_link' },
    { id: 212, title: 'Sapiens - Uma Breve História da Humanidade - Yuval Noah Harari', author: '', cover: 'https://m.media-amazon.com/images/I/81BTkpMrLYL.jpg', audio: 'https://drive.google.com/file/d/1mGK4T0pqcI0kwtqo2apzXBkq_BSZ3wHh/view?usp=drive_link' },
    { id: 214, title: 'Scrum - A Arte de Fazer o Dobro de Trabalho na Metade do Tempo - Jeff Sutherland', author: '', cover: 'https://m.media-amazon.com/images/I/61qz75GrsvL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1NJbWSy0P4SVhsY0UDThZdBFXFSy1_2J_/view?usp=drive_link' },
    { id: 215, title: 'Segredos Mágicos da Sua Mente - David Medina', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBve1ylly43YgyjpdOQWZZf5NnCj-yf3yVDg&s', audio: 'https://drive.google.com/file/d/1EkH2nUu7I4G5WswsLJA2Uv51Tifzp8O1/view?usp=drive_link' },
    { id: 216, title: 'Seja Foda! - Caio Carneiro', author: '', cover: 'https://m.media-amazon.com/images/I/4152pe7g7xL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1XsMF_3bQG3rV060oGHwLj0kQhz1PBLfa/view?usp=drive_link' },
    { id: 217, title: 'Silvio Santos, a Biografia - Marcia Batista e Anna Medeiros', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu_mdmNYmdbQw7drT5Ids-PUU5_TRzNEU9lg&s', audio: 'https://drive.google.com/file/d/1xq5nEWD6_dyBDRwIsL5pSuYT486_jlos/view?usp=drive_link' },
    { id: 218, title: 'Slogan', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 219, title: 'Storytelling - Aprenda a Contar Histórias como Steve Jobs', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQg1wWSok70Cr0HMSwq2iGxGxdtjFixym_0w&sg', audio: 'https://drive.google.com/file/d/1uGlwLNx1ggcwlLMJl_xwWTzwl8tBVwnT/view?usp=drive_link' },
    { id: 220, title: 'Tabralhe 4 Horas Por Semana - Timothy Ferriss', author: '', cover: 'https://m.media-amazon.com/images/I/81nUthzU+xL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1W4YZuQS96FuGmo9LImIDspUVzZ0rj7r5/view?usp=drive_link' },
    { id: 221, title: 'Treinando a Emoção Para Ser Feliz - Augusto Cury', author: '', cover: 'https://www.amazon.com.br/Treinando-Emo%C3%A7%C3%A3o-Para-Ser-Feliz/dp/8542203909', audio: 'https://drive.google.com/file/d/1OEoUIPHMFDcvDP8X3e2E489WckjeUgU5/view?usp=drive_link' },
    { id: 222, title: 'Um Caso Perdido - Colleen Hoover', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 223, title: 'Uma Breve História do Tempo - Stephen Hawking', author: '', cover: 'https://m.media-amazon.com/images/I/61AaXcdHXKS.jpg', audio: 'https://drive.google.com/file/d/1XL53TYJkyYjOgqC3SSJxyYJPbRiiLmNN/view?usp=drive_link' },
    { id: 224, title: 'Verity - Colleen Hoover', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgti-9UzkJPdeyFOTgFmNgxLAyTdKMKT-PFA&s', audio: 'https://drive.google.com/file/d/1sXNfnbX5rT6CiiQVpylKJ0_PKH2BqG8V/view?usp=drive_link' },
    { id: 225, title: 'Viagem ao Centro da Terra - Julio Verne', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQjCQQAoHSU5JoPIMccCyAlbkXuaoCnedFEg&s', audio: 'https://drive.google.com/file/d/1TRdgs1a8Ch2sy438DyrLSUqiutxoV9Mx/view?usp=drive_link' },
    { id: 226, title: 'Você Mais Inteligente - Técnicas de Gestão da Emoção para Revolucionar sua Vida - Augusto Cury', author: '', cover: 'https://m.media-amazon.com/images/I/71usc+CLl1L._UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/11CgW_H3ORe55nCwsDlH3pmfajGV7rlI_/view?usp=drive_link' },
    { id: 227, title: 'Você Nasceu Rico - Bob Proctor', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrUkdw24i0fkKLZcwDP7NOsY8Hx7A5dmiXhw&s', audio: 'https://drive.google.com/file/d/1x_-oM78CKSd_HxZszwuiYfaixjAaPfiX/view?usp=drive_link' },
    { id: 228, title: 'Wall Street - Raiam Santos', author: '', cover: 'https://m.media-amazon.com/images/I/719907u2lxL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1dZYHqMD04TyYJCyB-RstBot3eOGpPt1W/view?usp=drive_link' },
    { id: 229, title: 'Crime e Castigo - Parte 1 - Fíodor Dostoiévski', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8r14bjAHao2-NcOoBv2LL7ZLT1xrafz440w&s', audio: 'https://drive.google.com/file/d/1dGqmODD4TY6XmYCLHaK01AVOsRcEzooH/view?usp=drive_link' },
    { id: 231, title: 'Assim que Acaba - Colleen Hoover', author: '', cover: 'https://m.media-amazon.com/images/I/91r5G8RxqfL.jpg', audio: 'https://drive.google.com/file/d/1oHMuQgGg3P03pEzVq3KkEpU53MiDXkSJ/view?usp=drive_link' },
    { id: 232, title: 'Dom Casmurro - Machado de Assis - Audiobook Completo', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgMTQSRTxebu23ybPIL4PYeuSz3ygmjbjA8A&s', audio: 'https://drive.google.com/file/d/1yRGjz0r6NiEU0SP_grifVtmb-3AfGnJ9/view?usp=drive_link' }
  ],

  // ── EBOOKS ───────────────────────────────────────────────
  ebooks: [
    {
      id: 1,
      title: 'Mindset — Carol S. Dweck',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    },
    {
      id: 2,
      title: 'Antifrágil — Nassim Taleb',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    },
    {
      id: 3,
      title: 'Rápido e Devagar — Daniel Kahneman',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    },
    {
      id: 4,
      title: 'Gatilhos Mentais — Gustavo Ferreira',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    },
    {
      id: 5,
      title: 'Os 7 Hábitos — Stephen Covey',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    },
    {
      id: 6,
      title: 'A Arte da Guerra — Sun Tzu',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    },
    {
      id: 7,
      title: 'O Ego é Seu Inimigo — Ryan Holiday',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    },
    {
      id: 8,
      title: 'A Psicologia Financeira — Morgan Housel',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    }
  ],

  // ── BÔNUS ────────────────────────────────────────────────
  bonus: [
    {
      id: 1,
      title: 'Pasta Completa de Audiobooks',
      desc: 'Acesse todos os audiobooks disponíveis na coleção completa.',
      url: 'https://drive.google.com/drive/folders/SEU_FOLDER_ID_AQUI'
    },
    {
      id: 2,
      title: 'Pasta Completa de eBooks',
      desc: 'Mais de 3.000 títulos em PDF prontos para baixar.',
      url: 'https://drive.google.com/drive/folders/SEU_FOLDER_ID_AQUI'
    },
    {
      id: 3,
      title: 'Material Extra — Resumos',
      desc: 'Resumos dos principais best-sellers para leitura rápida.',
      url: 'https://drive.google.com/drive/folders/SEU_FOLDER_ID_AQUI'
    }
  ],

  // ── CONFIG ───────────────────────────────────────────────
  whatsapp: '5511999999999',  // Número com DDI + DDD, sem espaços ou símbolos
  whatsappMsg: 'Olá! Preciso de suporte com o LV Books.'
};