// ============================================================
//  LV Books — Dados do app
//  Edite aqui para adicionar/remover audiobooks, eBooks e bônus
// ============================================================

// Para links do Google Drive use o formato:
//   https://drive.google.com/uc?export=download&id=SEU_FILE_ID
// O FILE_ID está na URL de compartilhamento:
//   drive.google.com/file/d/  >FILE_ID<  /view

var LVData = {

  // ── AUDIOBOOKS ────────────────────────────────────────────
  audiobooks: [
    {
  id: 1,
  title: '1 Ano em 12 Semanas - Brian P. Moran e Michael Lennington',
  author: '',
  cover: 'https://m.media-amazon.com/images/I/716Xx+6GJiS.jpg',
  audio: 'https://drive.google.com/file/d/1Kz-vm_bTi7mt6o0oLLqZ74Iwx3QErz3M/view?usp=drive_link'
},
    { id: 2, title: '100 Homens que a História do Mundo - Bill Yenne', author: '', cover: 'https://m.media-amazon.com/images/I/511fsUG82UL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1atURJtgR-AOVtkgZ_1CbPJjHHoIEpL1X/view' },
    { id: 3, title: '12 Regras para a Vida - Jordan B. Peterson - Parte 1 de 2', author: '', cover: 'https://m.media-amazon.com/images/I/71geoUmEoQL.jpg', audio: 'https://drive.google.com/file/d/10yU_goy4KK-2e-FvVydMhyi8FJN0kVxg/view?usp=drive_link' },
    { id: 4, title: '12 Regras para a Vida - Jordan B. Peterson - Parte 2 de 2', author: '', cover: 'https://m.media-amazon.com/images/I/71geoUmEoQL.jpg', audio: 'https://drive.google.com/file/d/1XE1yWUCcc8NAF8FVVC0au4YcyijBgCGK/view?usp=drive_link' },
    { id: 6, title: '12 Semanas Para Mudar Uma Vida - Augusto Cury', author: '', cover: 'https://m.media-amazon.com/images/I/61x7NtR5IoL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1sXYJZpI6aNsy4T_e8JNpX0Dz2p8iMuoX/view?usp=drive_link' },
    { id: 7, title: '1984 - George Orwell', author: '', cover: 'https://m.media-amazon.com/images/I/61t0bwt1s3L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1LyzP-97-65kJGk9-9AdN1745NzLsIpbn/view?usp=drive_link' },
    { id: 8, title: '23 Hábitos Anti-Procrastinação - S.J. Scott', author: '', cover: 'https://m.media-amazon.com/images/I/81lwpqg9QjL._UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1Xh1OlEAaA_TfarpPvNDMP1pzqdhEwhDa/view?usp=drive_link' },
    { id: 9, title: '27 Poderes de Persuasão - Chris St. Hilaire e Lynette Padwa', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2bL_-OhoNbCSf96P3ygEtpjyUzkNn_mPCMA&s', audio: '' },
    { id: 10, title: '29 Minutos para Falar Bem em Público - Reinaldo Piloto e Rachel Polito', author: '', cover: 'https://m.media-amazon.com/images/I/51s91VGATPL.jpg', audio: 'https://drive.google.com/file/d/1K9wJzz0XlpY3Yf10pEvGS7h6JOuoLbGi/view?usp=drive_link' },
    { id: 11, title: '38 Estratégias para Vencer Qualquer Debate - Arthur Schopenhauer', author: '', cover: 'https://m.media-amazon.com/images/I/A1yeZ0JiKzL._UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/14_iI0jG0zHy5ikRK3PCVwJZ_wWaNzykw/view?usp=drive_link' },
    { id: 12, title: '52 Maneiras de Ganhar Mais Dinheiro - Clene Salles', author: '', cover: 'https://m.media-amazon.com/images/I/81k7SgjSQfL._UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1jZG_LYvFxdejZjT6bQRXeHfGZ6CmeFfY/view?usp=drive_link' },
    { id: 13, title: '60 Estratégias Práticas para Ganhar mais Tempo - Christian Barbosa', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTI516sXanP3GQftQFvg-EhhbKfhVsrBwd6mQ&s', audio: 'https://drive.google.com/file/d/1Njn65RTsBWXtmvkE_M5M9aHaOpSCkkC_/view?usp=drive_link' },
    { id: 14, title: '7 Lições De Negócios De La Casa De Papel - Fabio Bandeira de Melo', author: '', cover: 'https://m.media-amazon.com/images/I/61Pj39C0npL.jpg', audio: 'https://drive.google.com/file/d/1sUXeOitWJWeNdrmcACUdWF3Ayb00Ce_8/view?usp=drive_link' },
    { id: 15, title: 'A Arquitetura do Eu - Leonardo Mascaro', author: '', cover: 'https://m.media-amazon.com/images/I/81ckGa4rTGL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1e-ddtMuWGAddAqU25JOp_49Q4_20u31H/view?usp=drive_link' },
    { id: 16, title: 'A Arte da Guerra - Sun Tzu', author: '', cover: 'https://m.media-amazon.com/images/I/51Fe45NGwkL.jpg', audio: 'https://drive.google.com/file/d/1XlHo8yoEyc8VW4W8UuB27GKGKFdcdUV2/view?usp=drive_link' },
    { id: 17, title: 'A Arte da Negociação - Donald Trump', author: '', cover: 'https://m.media-amazon.com/images/I/71rFjbVqioL.jpg', audio: 'https://drive.google.com/file/d/1NYP84rtPqJjiwxgPMn8WYiIM0vXGO8ZS/view?usp=drive_link' },
    { id: 18, title: 'A Arte da Sedução - Robert Greene', author: '', cover: 'https://m.media-amazon.com/images/I/61rQikkGR9L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/19kh4k3aip4WDgYqKQh5TWZEPIdVGR4qE/view?usp=drive_link' },
    { id: 19, title: 'A Arte de Escrever para Web - Paulo Macedo', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxreQW3zOmr5EAdEqRvCz_SdzwVYOTJnwEvA&s', audio: 'https://drive.google.com/file/d/1WVdmLaONNTOXS-MF16__s6_6reNjInS9/view?usp=drive_link' },
    { id: 20, title: 'A Arte de Viver - Epicteto - Audiobook Completo', author: '', cover: 'https://m.media-amazon.com/images/I/81G1s-jiYKL._UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1H-_ImhJbAI1esuA5i2_I3y8KLNsO28Qu/view?usp=drive_link' },
    { id: 22, title: 'A Árvore do Dinheiro - Jurandir Sell Macedo Jr', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwJnz2PkM7JKj03RyhLRhJU-Vr6bF4jwbeUw&s', audio: 'https://drive.google.com/file/d/132t1n18cl6S1R9EvYhE_a8V54ohMGGjh/view?usp=drive_link' },
    { id: 23, title: 'A Ascensão do Dinheiro - Niall Ferguson', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-VgKj3LvySGq314tQBCgeVtgig0Qvjc5h_Q&s', audio: 'https://drive.google.com/file/d/1pYASnoViHB8R6t15vnR7pTUd6ScfVaZI/view?usp=drive_link' },
    { id: 24, title: 'A Cabala do Dinheiro - Nilton Bonder', author: '', cover: 'https://m.media-amazon.com/images/I/51JdilXoweL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/11ObupMlnX0zvI7R3jVjQzb1vnwF0Hx0n/view?usp=drive_link' },
    { id: 25, title: 'A Cabana - William P. Young', author: '', cover: 'https://m.media-amazon.com/images/I/91fLBlcmpXL.jpg', audio: 'https://drive.google.com/file/d/1bRUiRNuaruSL000csSfhGK3fLDSQtqI9/view?usp=drive_link' },
    { id: 26, title: 'A Cabeça de Steve Jobs - Liderança', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZ1gI-2-SwlsnN2iM8B1FIxRF7GQKTmYAiRw&s', audio: 'https://drive.google.com/file/d/1h7J5z0ZmLm7IH_ex3bTuONOjy5VFdb2x/view?usp=drive_link' },
    { id: 27, title: 'A Cabeça Do Investidor - Vera Rita de Mello Ferreira', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6JR45MwAkr6Bq2Ymok5k_3L_LJ0yw6uO-Ew&s', audio: 'https://drive.google.com/file/d/1_J85qd3xQGb-8ke6Xf-SQPXylwHb-Izk/view?usp=drive_link' },
    { id: 28, title: 'A Chave Mestra das Riquezas - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/61HWnfnDrWS._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1sSz4vMkrIMcfL2eX7HWxoltyoOev_rku/view?usp=drive_link' },
    { id: 29, title: 'A Chave Mestra do Universo - Pablo Marçal', author: '', cover: 'https://m.media-amazon.com/images/I/712qlBX9PzL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1jTNa0_oWePT8NAcoZla1X2Iu2wGQfmH8/view?usp=drive_link' },
    { id: 31, title: 'A Chave para a Prosperidade - Napoleon Hill', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS94P7WdlRzw3Rc68IV9u8lH93BlWKIBPpnBQ&s', audio: 'https://drive.google.com/file/d/1sSz4vMkrIMcfL2eX7HWxoltyoOev_rku/view?usp=drive_link' },
    { id: 32, title: 'A Ciência de Ficar Rico - Wallace D. Wattles', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAFKISyDhkg_6FLpK3ETRp0k2P4eFXXqF-1g&s', audio: 'https://drive.google.com/file/d/1wO7Me85WzRo2cDDd5idfjBGm6ZXoyzjK/view?usp=drive_link' },
    { id: 34, title: 'A Ciência do Sucesso - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/91FQBKRKkKL.jpg', audio: 'https://drive.google.com/file/d/1wO7Me85WzRo2cDDd5idfjBGm6ZXoyzjK/view?usp=drive_link' },
    { id: 35, title: 'A Coragem de Ser Imperfeito - Brené Brown', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfSCSaBXxJc22xpiMR9XMq5h7QbBvLReipBA&s', audio: 'https://drive.google.com/file/d/1UmEh6mcFrcv4ahCaOBipDgkJk1J3I07D/view?usp=drive_link' },
    { id: 36, title: 'A Escada para o Triunfo - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/61OeOmvi1ZL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1_fBfqry_jSDthq9Jr6f5dB_uZ1EMsF6S/view?usp=drive_link' },
    { id: 38, title: 'A Estratégia do Oceano Azul - Renée Mauborgne, W. Chan Kim', author: '', cover: 'https://m.media-amazon.com/images/I/71zvq8BIkmL._AC_UF1000,1000_QL80_.jpg', audio: 'https://m.media-amazon.com/images/I/71zvq8BIkmL._AC_UF1000,1000_QL80_.jpg' },
    { id: 39, title: 'A Fascinante Construção Do Eu - Augusto Cury', author: '', cover: 'https://m.media-amazon.com/images/I/61HFLB5b5aL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1yELAVkGz6HVRJ2o_KEPLFVvJ-0HziK5j/view?usp=drive_link' },
    { id: 40, title: 'A Filosofia Do Sucesso - Napoleon Hill', author: '', cover: 'https://m.media-amazon.com/images/I/51heT5W9YUL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1-UkSv3bBWZznRrfqaEnpuKcM76AyrvLH/view?usp=drive_link  ' },
    { id: 41, title: 'A Introdução Definitiva a PNL - Richard Bandler', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2pL_8SxSvgu_o-W-8dDk29ej6afLUA8A57g&s', audio: 'https://drive.google.com/file/d/1k2rf-vxKiu7ZZVaks4guz1cyA-oHl8BQ/view?usp=drive_link' },
    { id: 43, title: 'A Lei da Atração - O Segredo Colocado em Prática - Michael J. Losier', author: '', cover: 'https://m.media-amazon.com/images/I/71aphXwg+bL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1WZO-iOY9Of6uk9bvpEOyvcYRiOwKkzCm/view?usp=drive_link' },
    { id: 44, title: 'A Marca da Vitória - A História da NIKE - Philip H. Knight', author: '', cover: 'https://http2.mlstatic.com/D_NQ_NP_821751-MLA79585916267_092024-O.webp', audio: 'https://drive.google.com/file/d/17GGrjhKFJqXgVZ40YoTHuCpeXRYQBWI-/view?usp=drive_link' },
    { id: 45, title: 'A Mente Acima do Dinheiro - Faça as Pazes com seu Dinheiro - Ted Klontz, Brad Klontz', author: '', cover: 'https://m.media-amazon.com/images/I/61T1NwrRmAL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/10No1p0ZgEMV2OVKi2LXV6OI4PIntmSMI/view?usp=drive_link' },
    { id: 47, title: 'A Morte é um Dia que Vale a Pena Viver - Ana Cláudia Quintana Arantes', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRt7WmzUW3GS8qIH-QgKcMT2Lg5eqtp_ZFrzQ&s', audio: 'https://drive.google.com/file/d/1cgyEJszzhm5fNSJkppHXbtRBQjE32Sic/view?usp=drive_link' },
    { id: 48, title: 'A Mágica da Arrumação - Marie Kondo', author: '', cover: 'https://m.media-amazon.com/images/I/81HKBLcErZL.jpg', audio: 'https://drive.google.com/file/d/1ct91EMp6bwjhUQM7ztCJJNfxSdOWyfkV/view?usp=drive_link' },
    { id: 49, title: 'A Paixão Segundo G.H. - Clarice Lispector', author: '', cover: 'https://m.media-amazon.com/images/I/71MOAylrC+L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/17zuGd3vmqKnbJZ93FRtfa6Knw1BOhqYD/view?usp=drive_link' },
    { id: 50, title: 'A Psicologia Financeira - Morgan Housel', author: '', cover: 'https://m.media-amazon.com/images/I/71vZp6yONLL.jpg', audio: 'https://drive.google.com/file/d/1r0f3sf8MrqJ1KecABrRVdtpxDzexttcZ/view?usp=drive_link' },
    { id: 51, title: 'A Realização Espontânea do Desejo - Deepak Chopra', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJV37zn_rzXYW4VBROW2yvC-K4iH-St9qhYw&s', audio: 'https://drive.google.com/file/d/1EyqR_YzideDCbj_uCi1lJWIhHakNh7l0/view?usp=drive_link' },
    { id: 52, title: 'A Revolução 8020, O Poder da Escolha - Richard Koch', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFHCaH9cYuC93n80CaK2Q0EI3MkjBPGxmTZw&s', audio: 'https://drive.google.com/file/d/1kFvrdUkQRF6Cn9ECATjBmjo5D5s0oT6F/view?usp=drive_link' },
    { id: 53, title: 'A Revolução dos Bichos - George Orwell', author: '', cover: 'https://m.media-amazon.com/images/I/91BsZhxCRjL.jpg', audio: 'https://drive.google.com/file/d/1ZdqF6EaLAlk5ft67puGfB7L_NgIvq6gu/view?usp=drive_link' },
    { id: 54, title: 'A Sorte Segue a Coragem - Mario Sergio Cortella', author: '', cover: 'https://m.media-amazon.com/images/I/81LVMS26UtL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1evaz-F2HPrMmwtgtuG6iai82L-cs8nMh/view?usp=drive_link' },
    { id: 56, title: 'A Sutil Arte de Ligar o Foda-se - Mark Manson', author: '', cover: 'https://m.media-amazon.com/images/I/6175IU0qFgL.jpg', audio: 'https://drive.google.com/file/d/1y0WXuBt7et2j64Q6ATK68Z0DVUui2eAj/view?usp=drive_link ' },
    { id: 57, title: 'A Tríade do Tempo - Christian Barbosa', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsjB0-9dbeK3Ni5qLiQVmFcZdC8OlxnaVBmA&s', audio: 'https://drive.google.com/file/d/1T-T-atbkCw_13vUdi_wX2f6Xuce4GVOV/view?usp=drive_link' },
    { id: 58, title: 'Admirável Mundo Novo - Aldous Huxley', author: '', cover: 'https://m.media-amazon.com/images/I/61hOp6UFvCL._AC_UF1000,1000_QL80_DpWeblab_.jpg', audio: 'https://drive.google.com/file/d/13yXJUO8GaG9KDhFc3whdfdBiBWCc2JFw/view?usp=drive_link' },
    { id: 59, title: 'Antimedo - Pablo Marçal', author: '', cover: 'https://m.media-amazon.com/images/I/61BsXDaRO8L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1cvOjlQRMa58ZRTSdo7Wbr2pXZ3VVFIkk/view?usp=drive_link' },
    { id: 60, title: 'Arriscando a Própria Pele - Nassim Nicholas Taleb', author: '', cover: 'https://m.media-amazon.com/images/I/61sb8kdjBqL.jpg', audio: 'https://drive.google.com/file/d/1YIfYsgfztoEEZpXMYaBv4ykB7akwZ8T9/view?usp=drive_link' },
    { id: 61, title: 'Arrume a Sua Cama - William H. McRaven', author: '', cover: 'https://m.media-amazon.com/images/I/81C7jAnjS3L._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/112iwSVHfc6uu05N3Gqo3BLNi7_fWNioG/view?usp=drive_link' },
    { id: 62, title: 'As 21 Indispensáveis Qualidades de um Líder - John C. Maxwell', author: '', cover: 'https://m.media-amazon.com/images/I/81QzYgUjxRL.jpg', audio: 'https://drive.google.com/file/d/1cOKceECN_98Zub7A22d00fZUGFOL-2I7/view?usp=drive_link' },
    { id: 63, title: 'As 25 Leis Bíblicas do Sucesso', author: '', cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMjIL1HicwlbpxhEgG13DKryAQMM210L9DQw&s', audio: 'https://drive.google.com/file/d/1rV1etFcjbO1uIjI4ebHWaI1hqwK-uUOk/view?usp=drive_link' },
    { id: 64, title: 'As 48 Leis do Poder - Robert Greene', author: '', cover: 'https://m.media-amazon.com/images/I/617iS--XOQL._AC_UF1000,1000_QL80_.jpg', audio: 'https://drive.google.com/file/d/1pvqhnZz4DkDxOhUjb0hgUdlPd-Z6wQTM/view?usp=drive_link' },
    { id: 65, title: 'As 5 Linguagens do Amor - Gary Chapman', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 66, title: 'As Armas da Persuasão - Robert B. Cialdini', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 67, title: 'As Cinco Habilidades Essenciais do Relacionamento - Dale Carnegie', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 68, title: 'As Coisas Que Você Só Vê Quando Desacelera - Haemin Sunim', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 69, title: 'As Memórias de Sherlock Holmes - Arthur Conan Doyle', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 70, title: 'As Regras Básicas de Warren Buffett - Jeremy C. Miller', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 71, title: 'As Regras de Ouro dos Casais Saudáveis - Augusto Cury', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 72, title: 'Assim Falou Zaratustra - Friedrich Nietzsche', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 73, title: 'Assuma o Controle Do Seu Tempo - Holly Reisem Hanna', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 74, title: 'Atitude Mental Positiva - Napoleon Hill', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 75, title: 'Sobre a Brevidade da Vida - Caminhos da Sabedoria em Áudio', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 76, title: 'Bitcoin - A Moeda na Era Digital - Fernando Ulrich', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 77, title: 'Capitão da Minha Alma - Seja Dono da Sua Própria Mente - Napoleon Hill', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 78, title: 'Cartas A Um Jovem Investidor - Gustavo Cerbasi', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 79, title: 'Cartas de um Diabo a seu Aprendiz - C. S. Lewis', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 80, title: 'Casais Inteligentes Enriquecem Juntos - Gustavo Cerbasi', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 81, title: 'Casamento Blindado - Renato e Cristiane Cardoso', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 82, title: 'Comece Pelo Mais Difícil - Brian Tracy', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 83, title: 'Comece Pelo Porquê - Simon Sinek', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 84, title: 'Como Aprendi a Pensar - Luiz Felipe Pondé', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 85, title: 'Como Atrair Dinheiro - Joseph Murphy', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 86, title: 'Como Aumentar o Seu Próprio Salário - Napoleon Hill', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 87, title: 'Como Chegar ao Sim - William Ury, Roger Fisher', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 88, title: 'Como Convencer Alguém em 90 Segundos - Nicholas Boothman', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 89, title: 'Como Evitar Preocupações e Começar a Viver - Dale Carnegie', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 90, title: 'Como Fazer Alguém Gostar de Você em 90 Segundos - Nicholas Boothman', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 91, title: 'Como Fazer Amigos e Influenciar Pessoas - Dale Carnegie', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 92, title: 'Como Ganhar Dinheiro na Internet - 45 Formas Comprovadas - Thiago Vertad', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 93, title: 'Como Lidar Com Pessoas Manipuladoras - George K. Simon', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 94, title: 'Como Organizar Sua Vida Financeira - Gustavo Cerbasi', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 95, title: 'Como Parar de Se Preocupar e Começar a Viver - Dale Carnegie', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 96, title: 'Como Se Tornar Inesquecível - Dale Carnegie', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 97, title: 'Como Ser um Imã para o Dinheiro - Bruno Gimenes', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 98, title: 'Como Vender Na Crise e Aumentar Seus Lucros - Magno A. Sipaúba', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 99, title: 'Copywriting - Volume 2 - A Habilidade de Ouro Usada por Milionários - Paulo Macedo', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 100, title: 'Crer ou Não Crer - Padre Fábio de Mello e Leandro Karnal', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 101, title: 'Criação de Riqueza - Uma Metodologia Simples e Poderosa - Paulo Vieira', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 102, title: 'Curso Sobre Domínio Em Liderança - Dale Carnegie', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 103, title: 'De Zero a Um - Peter Thiel', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 104, title: 'Decifre e Influencie Pessoas - Paulo Vieira', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 105, title: 'Desbloqueie o Poder da Sua Mente - Michael Arruda', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 106, title: 'Desperte o Milionário que Há em Você - Nicholas Boothman', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 107, title: 'Do Mil Ao Milhão - Thiago Nigro', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 108, title: 'Do Zero ao Milhão - Carlos Wizard', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 109, title: 'Empresas Feitas Para Vencer - Jim Collins', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 110, title: 'Enriquecer - Ambição de Muitos, Realização de Poucos - Lair Ribeiro', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 111, title: 'Escola de Negócios - Robert T. Kiyosaki', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 112, title: 'Especialista em Pessoas - Tiago Brunet', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 113, title: 'Essencialismo - Greg McKeown', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 114, title: 'Eu Vou te Ensinar a Ser Rico - Ben Zruel', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 115, title: 'Fator de Enriquecimento - Paulo Vieira', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 116, title: 'Faça Fortuna com Ações - Décio Bazin', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 117, title: 'Filhos Inteligentes Enriquecem Sozinhos - Gustavo Cerbasi', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 118, title: 'Foco - O Poder da Única Coisa - Vinicius Almeida', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 119, title: 'Gatilhos Mentais - Gustavo Ferreira', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 120, title: 'Gente Pobre - Fíodor Dostoiévski', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 121, title: 'Geração de Valor - Flávio Augusto da Silva', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 122, title: 'Hackeando Tudo - Raiam Dos Santos', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 123, title: 'Harry Potter e a Pedra Filosofal - J. K. Rowling', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 124, title: 'HomoDeus - Yuval Noah Harari', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 125, title: 'Hábitos Atômicos - James Clear', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 127, title: 'Hábitos Milionários - Napoleon Hill', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 128, title: 'Ikigai - Os Segredos Dos Japoneses Para Uma Vida Longa e Feliz - Hector Garcia, Francesc Miralles', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 129, title: "Limite Zero (Ho'oponopono) - Joe Vitale", author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 130, title: 'Linguagem e Persuasão - Adilson Citelli', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 132, title: 'Mais Esperto que o Diabo - Napoleon Hill', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 133, title: 'Manual de Persuasão do FBI - Jack Shafer e Marvin Karlins', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 134, title: "Manual de Programação Neurolinguística PNL - Joseph O'Connor", author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 135, title: 'Marketing 5.0 - Philip Kotler', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 136, title: 'Me Poupe! - Nathalia Arcuri', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 137, title: 'Menos é Mais - Francine Jay', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 138, title: "Mentes Brilhantes - Alberto Dell'Isola", author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 139, title: 'Mindset - A Nova Psicologia do Sucesso - Carol Dweck', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 140, title: 'Mini Hábitos - Stephen Guise', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 141, title: 'Moby Dick - Herman Melville', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 142, title: 'Nascido Para o Sucesso - Colin Turner', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 143, title: 'Nação Dopamina - Anna Lembke', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 144, title: 'Negocie Como se Sua Vida Dependesse Disso - Christopher Voss, Tahl Raz', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 145, title: 'Negocie Qualquer Coisa com Qualquer Pessoa - Eduardo Ferraz', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 146, title: 'Nocaute - Gary Vaynerchuk', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 147, title: 'Nunca Desista De Seus Sonhos - Augusto Cury', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 148, title: "Nunca Foi Sorte - Adrianna Sant'anna", author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 149, title: 'Nós Queremos que Você Fique Rico - Donald Trump, Robert Kiyosaki', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 150, title: 'O Alquimista - Audiobook Completo - Narração Profissional', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 151, title: 'O Banquete - Platão - Audiobook Completo', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 152, title: 'O Cavaleiro dos Sete Reinos - George R.R. Martin', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 153, title: 'O Clube Das 5 Da Manhã - Robin Sharma', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 155, title: 'O Corpo Fala - Pierre Weil e Roland Tompakow', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 156, title: 'O Código da Inteligência - Augusto Cury', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 157, title: 'O Ego é Seu Inimigo - Ryan Holiday', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 158, title: 'O Hobbit - Audiobook Completo - Narração Profissional', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 159, title: 'O Homem Mais Inteligente da História - Augusto Cury', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 160, title: 'O Homem Mais Rico da Babilônia - George Samuel Clason', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 161, title: 'O Homem é Aquilo que ele Pensa - James Allen', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 162, title: 'O Jeito Disney de Encantar os Clientes - Disney Institute', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 163, title: 'O Lobo de Wall Street - Jordan Belfort', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 164, title: 'O Maior Vendedor do Mundo - Og Mandino', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 165, title: 'O Manuscrito Original - Napoleon Hill', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 166, title: 'O Mensageiro Milionário - Brendon Burchard', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 167, title: 'O Milagre da Manhã - Hal Elrod', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 168, title: 'O Milagre da Manhã para Transformar seu Relacionamento - Hal Elrod', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 169, title: 'O Milionário Instantâneo - Marc Fisher', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 170, title: 'O Monge e o Executivo - James C. Hunter', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 171, title: 'O Negócio do Século XXI - Robert Kiyosaki', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 172, title: 'O Pequeno Príncipe - Antoine de Saint-Exupéry', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 173, title: 'O Poder da Ação - Paulo Vieira', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 174, title: 'O Poder da Resiliência - Rick Hanson', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 175, title: 'O Poder do Agora - Eckhart Tolle', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 177, title: 'O Poder do Hábito - Charles Duhigg', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 178, title: 'O Poder do Subconsciente - Joseph Murphy', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 179, title: 'O Poder dos 5 Segundos - Mel Robbins', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 180, title: 'O Príncipe - Nicolau Maquiavel', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 182, title: 'O que Steve Jobs Faria - Peter Sander', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 183, title: 'O Segredo (The Secret) - Rhonda Byrne', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 184, title: 'O Senhor dos Anéis - Livro 1 - A Sociedade do Anel - J. R. R. Tolkien', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 185, title: 'O Senhor dos Anéis - Livro 2 - A Sociedade do Anel - J. R. R. Tolkien', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 186, title: 'O Sentimento é o Segredo - Neville Goddard', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 187, title: 'O Sucesso Não Ocorre Por Acaso - Lair Ribeiro', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 188, title: 'O Universo Numa Casca De Noz - Stephen Hawking', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 189, title: 'O Vendedor de Sonhos - Augusto Cury', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 190, title: 'O Vinho Novo é Melhor - Robert Thom', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 191, title: 'Opúsculo Humanitário - Parte 1', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 192, title: 'Opúsculo Humanitário - Parte 2', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 193, title: 'Originais - Adam Grant', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 194, title: 'Os 100 Segredos Das Pessoas Felizes - David Niven', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 195, title: 'Os Códigos do Milhão - Pablo Marçal', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 197, title: 'Os Segredos Da Mente Milionária - T. Harv Eker', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 199, title: 'Pai Rico Pai Pobre - Robert Kiyosaki', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 201, title: 'Penso e Acontece - Bob Proctor', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 202, title: 'Poder e Manipulação - Jacob Petry', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 203, title: 'Ponto de Inflexão - Flávio Augusto da Silva', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 204, title: 'Por Que Fazemos O Que Fazemos - Mario Sergio Cortella', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 205, title: 'Prosperidade - 12 Passos para Alcançar o Sucesso - Charles Fillmore', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 206, title: 'Qual é a Tua Obra - Mário Sérgio Cortella', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 207, title: 'Quebrando o Hábito de Ser Você Mesmo - Joe Dispenza', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 208, title: 'Quem Assiste Enriquece - Napoleon Hill', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 210, title: 'Quem Pensa, Enriquece - Napoleon Hill', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 211, title: 'Salomão, O Homem Mais Rico que Já Existiu - Steven K. Scott', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 212, title: 'Sapiens - Uma Breve História da Humanidade - Yuval Noah Harari', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 214, title: 'Scrum - A Arte de Fazer o Dobro de Trabalho na Metade do Tempo - Jeff Sutherland', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 215, title: 'Segredos Mágicos da Sua Mente - David Medina', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 216, title: 'Seja Foda! - Caio Carneiro', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 217, title: 'Silvio Santos, a Biografia - Marcia Batista e Anna Medeiros', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 218, title: 'Slogan', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 219, title: 'Storytelling - Aprenda a Contar Histórias como Steve Jobs', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 220, title: 'Trabalhe 4 Horas Por Semana - Timothy Ferriss', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 221, title: 'Treinando a Emoção Para Ser Feliz - Augusto Cury', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 222, title: 'Um Caso Perdido - Colleen Hoover', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 223, title: 'Uma Breve História do Tempo - Stephen Hawking', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 224, title: 'Verity - Colleen Hoover', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 225, title: 'Viagem ao Centro da Terra - Julio Verne', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 226, title: 'Você Mais Inteligente - Técnicas de Gestão da Emoção para Revolucionar sua Vida - Augusto Cury', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 227, title: 'Você Nasceu Rico - Bob Proctor', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 228, title: 'Wall Street - Raiam Santos', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 229, title: 'Crime e Castigo - Parte 1 - Fíodor Dostoiévski', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 231, title: 'Assim que Acaba - Colleen Hoover', author: '', cover: '../audio%20book/1.jpg', audio: '' },
    { id: 232, title: 'Dom Casmurro - Machado de Assis - Audiobook Completo', author: '', cover: '../audio%20book/1.jpg', audio: '' }
  ],

  // ── EBOOKS ───────────────────────────────────────────────
  ebooks: [
    {
      id: 1,
      title: 'Mindset — Carol S. Dweck',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    },
    {
      id: 2,
      title: 'Antifrágil — Nassim Taleb',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    },
    {
      id: 3,
      title: 'Rápido e Devagar — Daniel Kahneman',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    },
    {
      id: 4,
      title: 'Gatilhos Mentais — Gustavo Ferreira',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    },
    {
      id: 5,
      title: 'Os 7 Hábitos — Stephen Covey',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    },
    {
      id: 6,
      title: 'A Arte da Guerra — Sun Tzu',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    },
    {
      id: 7,
      title: 'O Ego é Seu Inimigo — Ryan Holiday',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    },
    {
      id: 8,
      title: 'A Psicologia Financeira — Morgan Housel',
      url: 'https://drive.google.com/file/d/SEU_FILE_ID_AQUI/view'
    }
  ],

  // ── BÔNUS ────────────────────────────────────────────────
  bonus: [
    {
      id: 1,
      title: 'Pasta Completa de Audiobooks',
      desc: 'Acesse todos os audiobooks disponíveis na coleção completa.',
      url: 'https://drive.google.com/drive/folders/SEU_FOLDER_ID_AQUI'
    },
    {
      id: 2,
      title: 'Pasta Completa de eBooks',
      desc: 'Mais de 3.000 títulos em PDF prontos para baixar.',
      url: 'https://drive.google.com/drive/folders/SEU_FOLDER_ID_AQUI'
    },
    {
      id: 3,
      title: 'Material Extra — Resumos',
      desc: 'Resumos dos principais best-sellers para leitura rápida.',
      url: 'https://drive.google.com/drive/folders/SEU_FOLDER_ID_AQUI'
    }
  ],

  // ── CONFIG ───────────────────────────────────────────────
  whatsapp: '5511999999999',  // Número com DDI + DDD, sem espaços ou símbolos
  whatsappMsg: 'Olá! Preciso de suporte com o LV Books.'
};